name: Release Workflows Library

on:
  push:
    branches: [main, 'release/*']

permissions:
  contents: write

jobs:
  release:
    uses: calavia-org/workflows-lib/.github/workflows/release-github-action.yml@v0
    with:
      version-file: 'none'
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
